= Amplification Power and Voltage Calculator ~ dB dBm Watt Volt Amper

http://www.sengpielaudio.com/calculator-amplification.htm
http://www.sengpielaudio.com/calculator-db.htm


 3 dB ≡	 1.414 times the voltage	   (−)3 dB ≡	 damping to the value 0.707
 6 dB ≡	         2 times the voltage	   (−)6 dB ≡	 damping to the value 0.5
10 dB ≡	 3.162 times the voltage	   (−)10 dB ≡	 damping to the value 0.316
12 dB ≡	 4 times the voltage	   (−)12 dB ≡	 damping to the value 0.25
20 dB ≡	      10 times the voltage	    (−)20 dB ≡	 damping to the value 0.1

Using voltage we get: Level in dB: L = 20 × log (voltage ratio)

  6 dB = twice the voltage
12 dB = four times the voltage
20 dB = ten times the voltage
40 dB = hundred times the voltage
If we consider audio engineering, we are usually not interested in power.
Do not ask what power amplification means.
Leave that to the telephone companies or the transmitting aerials (antennas).
Power gain is really not used in audio engineering.
Do we really need power (energy) amplification?
Read the text at the bottom.

 3 dB ≡	 2 times the power	   (−3) dB ≡	 damping to the value 0.5
 6 dB ≡	         4 times the power	   (−6) dB ≡	 damping to the value 0.25
10 dB ≡	 10 times the power	   (−10) dB ≡	 damping to the value 0.1
12 dB ≡	 16 times the power	   (−12) dB ≡	 damping to the value 0.0625 
20 dB ≡	      100 times the power	    (−20) dB ≡	 damping to the value 0.01
Using power we get: Level in dB: L = 10 × log (power ratio)


   3 dB = twice the power
   6 dB = four times the power
 10 dB = ten times the power
 20 dB = hundred times the power 
If you search for the amplification ratio, given the dB value,
then go to the program dB calculation